# Site settings
title: "李慧的个人主页"
description: "个人主页"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "李慧"
resume_title:                   "个人简历"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "15732157372@163.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "15732157372"
resume_contact_address:         "石家庄铁道大学"

resume_header_contact_info:     "石家庄铁道大学 • 15732157372 • m15732157372@163.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>生日：1997/06/21</p>
<p>所在城市：石家庄</p>
<p>职业类型：软件工程师</p>
<p>意向城市：郑州</p>
<p>自我总结：本科，今年大四，参加过相关软件大赛，包括创新创业、大学生软件设计大赛，并在大三考取了中级软件设计师，学习成绩还不错，获得过几次三好学生、优秀团员等称号，个人对于C#项目和Android项目是非常感兴趣的。</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_info:            true
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Rebecca3150"
  resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://Rebecca3150.github.io"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
